name: clean_router
version: 0.1.2
author: Clean Team <clean@vacuumlabs.com>
description: Routing library used in clean framework.
homepage: https://github.com/cleandart/clean_router
documentation: https://github.com/cleandart/clean_router
dependencies:
  browser: '>=0.9.0 <0.10.0'
  clean_data: '>=0.2.0 <0.3.0'
dev_dependencies:
  hop: any
  unittest: any
