name: clean_router
version: 0.1.1
authors:
- Samuel Hap√°k <samuel.hapak@vacuumapps.com>
- Peter Csiba <petherz@gmail.com>
- Jozef Brandys <jozef.brandys@gmail.com>
description: Routing requests both on client and server side.
homepage: https://github.com/cleandart/clean_router
dependencies:
  browser: any
  clean_data:
    git: https://github.com/cleandart/clean_data
dev_dependencies:
  unittest: any
