name: router
version: 0.0.0
author: Samuel Hap√°k <samuel.hapak@vacuumapps.com>
description: A sample web application
homepage: https://github.com/hleumas/dart-router
dependencies:
  unittest: any
  browser: any
  web_ui: any
  delegate: any
